#!/bin/sh
raw_port="6379"
filename="redis-${1}.conf"
pid="redis_${1}.pid"
log="redis-${1}.log"
rawpid="redis_6379.pid"
rawlog="redis.log"

cp redis.conf ${filename}
# 加个! 表示取反
if test ! -d /var/lib/redis${1} ; then  
mkdir /var/lib/redis${1}
fi
sed -i s/"port ${raw_port}"/"port ${1}"/ ${filename}
sed -i s/${rawpid}/${pid}/ ${filename}
sed -i s/${rawlog}/${log}/ ${filename}
sed -i s#lib/redis#lib/redis${1}# ${filename}

#斜杠解决方法用#作为分隔符
#一些坑 空格没法作为变量 待研究
#sed命令替换字符包含斜杠\，引号的处理方法
#在字符替换中，可能会遇见引号，“/”等的替换，这时应该注意，sed的命令原型是：

#sed -i  "s/oldstring/goalstring/g" file

#如果一个路径是data/path/abc,现在要将此路径换成一个字符串cde

#但是这时跟在s后边的其实是分隔符，用以将oldstring替换成cde;他可以使用任意字符，这时如果字符串中有“/”，就会发生混乱，在这个时候可以用#当做分隔符，就变成

#sed -i "s#abc#cde#g" file

#这时如果abc中包含“/”就可以随便替换了；

#引号的替换：

#需要将引号转义，使用反斜杠“\”，比如替换" ' 'div' ' "，如果需要将它替换成‘div' ;可以使用sed -i s#\"\'\'#\'#g就能替换了。
